name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pip
        run: python -m ensurepip

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install setuptools
        run: python -m pip install "setuptools==72.1.0"

      - name: Install wheel and twine
        run: python -m pip install wheel twine

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish package
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*